### ISSUE TITLE
Menu shouldn’t increment on the first press

### ISSUE THREAD

**Issue by sadiqawos** [sadiqawos/micro_light_meter#4]
The menu shouldn’t increment on the first press. It goes to the next item so you have to cycle through before you can make another change to the same value

**Comment by mattthegamer463** [comment]
Example: i change ISO, then take a sample.  When I press the menu button again, it sjould go to ISO again, but instead it goes to the next menu item.

**Comment by sadiqawos** [comment]
https://github.com/sadiqawos/micro_light_meter/pull/2/commits/eb8abee241bd9c8617b93325e6457c42e05100c5
