### ISSUE TITLE
Inverted left-right scroll direction

### ISSUE THREAD

**Issue by sadiqawos** [sadiqawos/micro_light_meter#6]
In the menu, left and right buttons count change the wrong way.  Left should lower the aperture number, lengthen time (increase exposure).  The right should increase the aperture number, shorten the time (decreased exposure). 

Might be opposite of the intuitive direction, I guess.

**Comment by mattthegamer463** [comment]
This has been corrected for the aperture values, but not the shutter values.  Left button shortens the shutter time and right lengthens the shutter time.  this should be reversed.
